language: node_js
node_js:
  - 14
branches:
  only:
    - master
script:
  - echo "skipping test"
  - npm format
  - npm lint
deploy:
  provider: heroku
  app: "group-drawing21"
  api_key:
    secure: "5d9befc5-6d8d-44d4-a000-75ecb6b426bc"
